### ISSUE TITLE
Please update Tawk plug-in for OpenCart 3

### ISSUE THREAD

**Issue by donhuvy** [tawk/tawk-opencart2#2]
@tawk-devj , Please update Tawk plug-in for OpenCart 3

Thank you!

**Comment by alvinjohnsonso** [comment]
Hi! Just giving you a heads up that there's a recent release for OpenCart 3! Here's the GitHub repository where future updates will be posted https://github.com/tawk/tawk-opencart3.

You can also download the plugin in the marketplace https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=16209&filter_member=tawkto.
